// metadata.ts
import { type Metadata } from "next";

export interface Icon {
  url: string;
}

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ url: "/horn2.png" }] as Icon[],  // Ensure icons is an array of objects with 'url' property
};

// icons: [{ rel: "icon", url: "/horn2.png" }],